Created configurable decimal formatter pattern
42BV/jarb-final-form pull request #42
Opened 2022-10-11 15:03 UTC by SanderBenschop

This is done on the jarbField level so you have
maximum control of the validation of the field
and the deserialization performed for that field
on the backend.

By default the current (American) number format
is used.

2022-10-13 14:52 UTC, gidomanders requested changes

2022-10-13 14:52 UTC, gidomanders commented on package.json
> -  "version": "3.0.0",
This was probably used for dev:publish, but it should not remain in this PR

2022-10-17 07:16 UTC, SanderBenschop commented on package.json
> -  "version": "3.0.0",
Reverted the version bumps.

2022-10-20 08:34 UTC, gidomanders approved these changes

2022-10-20 09:53 UTC, merged